// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: rpc.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PesoIdealClient is the client API for PesoIdeal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PesoIdealClient interface {
	CalculaPesoIdeal(ctx context.Context, in *PesoIdealRequest, opts ...grpc.CallOption) (*PesoIdealReply, error)
}

type pesoIdealClient struct {
	cc grpc.ClientConnInterface
}

func NewPesoIdealClient(cc grpc.ClientConnInterface) PesoIdealClient {
	return &pesoIdealClient{cc}
}

func (c *pesoIdealClient) CalculaPesoIdeal(ctx context.Context, in *PesoIdealRequest, opts ...grpc.CallOption) (*PesoIdealReply, error) {
	out := new(PesoIdealReply)
	err := c.cc.Invoke(ctx, "/pesoideal.PesoIdeal/CalculaPesoIdeal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PesoIdealServer is the server API for PesoIdeal service.
// All implementations must embed UnimplementedPesoIdealServer
// for forward compatibility
type PesoIdealServer interface {
	CalculaPesoIdeal(context.Context, *PesoIdealRequest) (*PesoIdealReply, error)
	mustEmbedUnimplementedPesoIdealServer()
}

// UnimplementedPesoIdealServer must be embedded to have forward compatible implementations.
type UnimplementedPesoIdealServer struct {
}

func (UnimplementedPesoIdealServer) CalculaPesoIdeal(context.Context, *PesoIdealRequest) (*PesoIdealReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculaPesoIdeal not implemented")
}
func (UnimplementedPesoIdealServer) mustEmbedUnimplementedPesoIdealServer() {}

// UnsafePesoIdealServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PesoIdealServer will
// result in compilation errors.
type UnsafePesoIdealServer interface {
	mustEmbedUnimplementedPesoIdealServer()
}

func RegisterPesoIdealServer(s grpc.ServiceRegistrar, srv PesoIdealServer) {
	s.RegisterService(&PesoIdeal_ServiceDesc, srv)
}

func _PesoIdeal_CalculaPesoIdeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PesoIdealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PesoIdealServer).CalculaPesoIdeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pesoideal.PesoIdeal/CalculaPesoIdeal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PesoIdealServer).CalculaPesoIdeal(ctx, req.(*PesoIdealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PesoIdeal_ServiceDesc is the grpc.ServiceDesc for PesoIdeal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PesoIdeal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pesoideal.PesoIdeal",
	HandlerType: (*PesoIdealServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculaPesoIdeal",
			Handler:    _PesoIdeal_CalculaPesoIdeal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
