// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PodeAposentarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idade        uint32 `protobuf:"varint,1,opt,name=idade,proto3" json:"idade,omitempty"`
	TempoServico uint32 `protobuf:"varint,2,opt,name=tempoServico,proto3" json:"tempoServico,omitempty"`
}

func (x *PodeAposentarRequest) Reset() {
	*x = PodeAposentarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodeAposentarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodeAposentarRequest) ProtoMessage() {}

func (x *PodeAposentarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodeAposentarRequest.ProtoReflect.Descriptor instead.
func (*PodeAposentarRequest) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *PodeAposentarRequest) GetIdade() uint32 {
	if x != nil {
		return x.Idade
	}
	return 0
}

func (x *PodeAposentarRequest) GetTempoServico() uint32 {
	if x != nil {
		return x.TempoServico
	}
	return 0
}

type PodeAposentarReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodeAposentar bool `protobuf:"varint,1,opt,name=podeAposentar,proto3" json:"podeAposentar,omitempty"`
}

func (x *PodeAposentarReply) Reset() {
	*x = PodeAposentarReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PodeAposentarReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodeAposentarReply) ProtoMessage() {}

func (x *PodeAposentarReply) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodeAposentarReply.ProtoReflect.Descriptor instead.
func (*PodeAposentarReply) Descriptor() ([]byte, []int) {
	return file_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *PodeAposentarReply) GetPodeAposentar() bool {
	if x != nil {
		return x.PodeAposentar
	}
	return false
}

var File_rpc_proto protoreflect.FileDescriptor

var file_rpc_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70, 0x6f,
	0x73, 0x65, 0x6e, 0x74, 0x61, 0x64, 0x6f, 0x72, 0x69, 0x61, 0x22, 0x50, 0x0a, 0x14, 0x50, 0x6f,
	0x64, 0x65, 0x41, 0x70, 0x6f, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x64, 0x61, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x69, 0x64, 0x61, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x65, 0x6d, 0x70,
	0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c,
	0x74, 0x65, 0x6d, 0x70, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x6f, 0x22, 0x3a, 0x0a, 0x12,
	0x50, 0x6f, 0x64, 0x65, 0x41, 0x70, 0x6f, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x6f, 0x64, 0x65, 0x41, 0x70, 0x6f, 0x73, 0x65, 0x6e,
	0x74, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70, 0x6f, 0x64, 0x65, 0x41,
	0x70, 0x6f, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x32, 0x6a, 0x0a, 0x0d, 0x41, 0x70, 0x6f, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x64, 0x6f, 0x72, 0x69, 0x61, 0x12, 0x59, 0x0a, 0x0d, 0x50, 0x6f, 0x64,
	0x65, 0x41, 0x70, 0x6f, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x6f,
	0x73, 0x65, 0x6e, 0x74, 0x61, 0x64, 0x6f, 0x72, 0x69, 0x61, 0x2e, 0x50, 0x6f, 0x64, 0x65, 0x41,
	0x70, 0x6f, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x61, 0x70, 0x6f, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x64, 0x6f, 0x72, 0x69, 0x61, 0x2e,
	0x50, 0x6f, 0x64, 0x65, 0x41, 0x70, 0x6f, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x55, 0x46, 0x47, 0x53, 0x69, 0x73, 0x74, 0x65, 0x6d, 0x61, 0x73, 0x44, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x69, 0x64, 0x6f, 0x73, 0x32, 0x30, 0x32, 0x33, 0x30, 0x31,
	0x2f, 0x47, 0x72, 0x75, 0x70, 0x6f, 0x34, 0x2f, 0x70, 0x72, 0x6f, 0x62, 0x6c, 0x65, 0x6d, 0x61,
	0x73, 0x2d, 0x72, 0x70, 0x63, 0x2f, 0x65, 0x78, 0x37, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_proto_rawDescOnce sync.Once
	file_rpc_proto_rawDescData = file_rpc_proto_rawDesc
)

func file_rpc_proto_rawDescGZIP() []byte {
	file_rpc_proto_rawDescOnce.Do(func() {
		file_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_proto_rawDescData)
	})
	return file_rpc_proto_rawDescData
}

var file_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_proto_goTypes = []interface{}{
	(*PodeAposentarRequest)(nil), // 0: aposentadoria.PodeAposentarRequest
	(*PodeAposentarReply)(nil),   // 1: aposentadoria.PodeAposentarReply
}
var file_rpc_proto_depIdxs = []int32{
	0, // 0: aposentadoria.Aposentadoria.PodeAposentar:input_type -> aposentadoria.PodeAposentarRequest
	1, // 1: aposentadoria.Aposentadoria.PodeAposentar:output_type -> aposentadoria.PodeAposentarReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_proto_init() }
func file_rpc_proto_init() {
	if File_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodeAposentarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PodeAposentarReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_proto_goTypes,
		DependencyIndexes: file_rpc_proto_depIdxs,
		MessageInfos:      file_rpc_proto_msgTypes,
	}.Build()
	File_rpc_proto = out.File
	file_rpc_proto_rawDesc = nil
	file_rpc_proto_goTypes = nil
	file_rpc_proto_depIdxs = nil
}
