all:
	go run queue.go ricart_agrawala.go message.go utils.go counter.go process.go main.go 

server:
	go run server/main.go

server_critical_region:
	go run server_critical_region/main.go

.PHONY: all server server_critical_region
