# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\raposentadoria\";\n\x14PodeAposentarRequest\x12\r\n\x05idade\x18\x01 \x01(\r\x12\x14\n\x0ctempoServico\x18\x02 \x01(\r\"+\n\x12PodeAposentarReply\x12\x15\n\rpodeAposentar\x18\x01 \x01(\x08\x32j\n\rAposentadoria\x12Y\n\rPodeAposentar\x12#.aposentadoria.PodeAposentarRequest\x1a!.aposentadoria.PodeAposentarReply\"\x00\x42MZKgithub.com/UFGSistemasDistribuidos202301/Grupo4/problemas-rpc/ex7/server/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZKgithub.com/UFGSistemasDistribuidos202301/Grupo4/problemas-rpc/ex7/server/pb'
  _PODEAPOSENTARREQUEST._serialized_start=28
  _PODEAPOSENTARREQUEST._serialized_end=87
  _PODEAPOSENTARREPLY._serialized_start=89
  _PODEAPOSENTARREPLY._serialized_end=132
  _APOSENTADORIA._serialized_start=134
  _APOSENTADORIA._serialized_end=240
# @@protoc_insertion_point(module_scope)
