# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rpc_pb2 as rpc__pb2


class PesoIdealStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CalculaPesoIdeal = channel.unary_unary(
                '/pesoideal.PesoIdeal/CalculaPesoIdeal',
                request_serializer=rpc__pb2.PesoIdealRequest.SerializeToString,
                response_deserializer=rpc__pb2.PesoIdealReply.FromString,
                )


class PesoIdealServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CalculaPesoIdeal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PesoIdealServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CalculaPesoIdeal': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculaPesoIdeal,
                    request_deserializer=rpc__pb2.PesoIdealRequest.FromString,
                    response_serializer=rpc__pb2.PesoIdealReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pesoideal.PesoIdeal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PesoIdeal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CalculaPesoIdeal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pesoideal.PesoIdeal/CalculaPesoIdeal',
            rpc__pb2.PesoIdealRequest.SerializeToString,
            rpc__pb2.PesoIdealReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
