# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\tpesoideal\"0\n\x10PesoIdealRequest\x12\x0c\n\x04sexo\x18\x01 \x01(\t\x12\x0e\n\x06\x61ltura\x18\x02 \x01(\x02\"#\n\x0ePesoIdealReply\x12\x11\n\tpesoIdeal\x18\x01 \x01(\x02\x32Y\n\tPesoIdeal\x12L\n\x10\x43\x61lculaPesoIdeal\x12\x1b.pesoideal.PesoIdealRequest\x1a\x19.pesoideal.PesoIdealReply\"\x00\x42NZLgithub.com/UFGSistemasDistribuidos202301/Grupo4/problemas-rpc/ex-4/server/pbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'ZLgithub.com/UFGSistemasDistribuidos202301/Grupo4/problemas-rpc/ex-4/server/pb'
  _PESOIDEALREQUEST._serialized_start=24
  _PESOIDEALREQUEST._serialized_end=72
  _PESOIDEALREPLY._serialized_start=74
  _PESOIDEALREPLY._serialized_end=109
  _PESOIDEAL._serialized_start=111
  _PESOIDEAL._serialized_end=200
# @@protoc_insertion_point(module_scope)
